# Source: jx-ui/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-ui
  labels:
    app.kubernetes.io/name: jx-ui
    app.kubernetes.io/instance: "jx-ui"
    helm.sh/chart: jx-ui-0.0.19
    app.kubernetes.io/version: "0.0.19"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'cluster'
  annotations:
    meta.helm.sh/release-name: 'jx-ui'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jx-ui
subjects:
- kind: ServiceAccount
  name: jx-ui
  namespace: jx
